server:
  port: 8081

user:
  photo:
    storage:
      url: ${USER_STORAGE_PHOTO_SERVICE_BASE_URL:http://localhost:8082/photo}
      readTimeout: ${USER_STORAGE_SERVICE_READ_TIMEOUT:1000}
      writeTimeout: ${USER_STORAGE_SERVICE_WRITE_TIMEOUT:1000}
      option: ${USER_STORAGE_SERVICE_OPTION:1000}

  info:
    url: ${USER_INFO_SERVICE_BASE_URL:http://localhost:8080/users}
    readTimeout: ${USER_INFO_SERVICE_READ_TIMEOUT:1000}
    writeTimeout: ${USER_INFO_SERVICE_WRITE_TIMEOUT:1000}
    option: ${USER_INFO_SERVICE_OPTION:1000}

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_CLIENT_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/client.log
    path: logs
